version: '2'
services:
 etna:
   image: '848510910118.dkr.ecr.eu-west-1.amazonaws.com/etna:demo-0'
   ports:
     - "8081:8081"
   volumes:
     - ./vhosts:/vhosts
     - ./commands:/commands
   links:
     - etna_mysql
     - redis
     - elasticsearch
     - jackrabbit
     - mary
   command: ["bash", "/vhosts/vhost.sh", "etna", "8081"]

 etna_mysql:
   image: 848510910118.dkr.ecr.eu-west-1.amazonaws.com/mysql:latest
   environment:
     - "MYSQL_ROOT_PASSWORD=root"
     - "MYSQL_DATABASE=20mn"
     - "MYSQL_USER=root"
     - "MYSQL_PASSWORD=root"
   ports:
     - "3306:3306"
   volumes:
     - /mnt/ebs-datastore/etna_mysql:/var/lib/mysql

 redis:
   image: 848510910118.dkr.ecr.eu-west-1.amazonaws.com/redis:latest
   ports:
     - "6379:6379"

 elasticsearch:
   image: 848510910118.dkr.ecr.eu-west-1.amazonaws.com/elasticsearch:1.7
   volumes:
     - /mnt/ebs-datastore/elasticsearch:/usr/share/elasticsearch/data
   ports:
     - "9200:9200"

 jackrabbit:
   image: 848510910118.dkr.ecr.eu-west-1.amazonaws.com/jackrabbit:latest
   ports:
       - "8080:8080"
   volumes:
     - /mnt/ebs-datastore/jackrabbit:/app/jackrabbit

 mary:
   image: '848510910118.dkr.ecr.eu-west-1.amazonaws.com/mary:demo-0'
   expose:
     - "8082"
   ports:
     - "8082:8082"
   volumes:
     - ./vhosts:/vhosts
   links:
     - redis
   command: ["bash", "/vhosts/vhost.sh", "mary", "8082"]
